on: push
#  schedule:
#    - cron: "0 0 * * *"
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ELMOTOKEN }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: pip install requests bs4
      - run: python scrape.py
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'appid.txt'
          author_name: 'Bot Scraper'
          author_email: 'lidder86@gmail.com'
          cwd: '.'
          default_author: github_actor
          message: 'Update appid txt'
          push: true
